language: python
os: linux
dist: jammy

python:
  - "3.10"
  - "3.11"
  - "3.12"

cache: pip

install:
  - python -m pip install --upgrade pip
  - python -m pip install .

script:
  - make smoke PYTHON=python TPLINKCTL=tplinkctl

branches:
  only:
    - main
